name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: unbuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Test SSH connection
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo SSH connection"

      - name: Deploy to EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          if [ ! -d "/home/${{secrets.EC2_USER}}/docker" ]; then
            git clone --recursive https://github.com/2024-Summer-Bootcamp-team-C/Docker
          fi
          cd Docker
          git pull origin main
          docker-compose down
          docker-compose up --build -d
          EOF
