name: CI Pipeline

on:
  push:
    branches:
      - main
      - Feat/#10
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest ./tests/test.py || exit 1

      # - name: Run Pylint
      #   run: |
      #     pylint app tests --rcfile=.pylintrc || exit 1
