name: CI Pipeline

on:
  push:
    branches:
      - main
      - Feat/#10
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
    	    submodules: true
    	    token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          cd backend
          ls -R

      - name: Install dependencies
        run: |
          if [ -f backend/requirements.txt ]; then
            pip install -r ./backend/requirements.txt
          else
            echo "requirements.txt not found"
            exit 1
          fi

      # - name: Run tests
      #   run: |
      #     pytest ./tests/test.py || exit 1
      #
      # - name: Run Pylint
      #   run: |
      #     pylint app tests --rcfile=.pylintrc || exit 1
